//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReviewAnalyzers.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReviewAnalyzers.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All public or protected items should have a summary comment..
        /// </summary>
        internal static string EmptySummary_Description {
            get {
                return ResourceManager.GetString("EmptySummary_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public or protected {0} {1} has an empty summary comment..
        /// </summary>
        internal static string EmptySummary_MessageFmt {
            get {
                return ResourceManager.GetString("EmptySummary_MessageFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary comment is empty..
        /// </summary>
        internal static string EmptySummary_Title {
            get {
                return ResourceManager.GetString("EmptySummary_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All public or protected items should have a summary comment..
        /// </summary>
        internal static string MissingSummary_Description {
            get {
                return ResourceManager.GetString("MissingSummary_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public or protected {0} {1} is missing a summary comment..
        /// </summary>
        internal static string MissingSummary_MessageFmt {
            get {
                return ResourceManager.GetString("MissingSummary_MessageFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary comment is missing..
        /// </summary>
        internal static string MissingSummary_Title {
            get {
                return ResourceManager.GetString("MissingSummary_Title", resourceCulture);
            }
        }
    }
}
